<?php

namespace NGPP\GmsagcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoldsRepository extends EntityRepository
{
    /**
     * Return last id+1 or null if not find
     * 
     * @return integer
     */
    public function getNewId()
    {
        $result = $this->createQueryBuilder('m')
                ->select('MAX(m.id)')
                ->getQuery()->getOneOrNullResult();
        
        return is_array($result) ? $result[1] + 1 : null;
    }
}
