<?php

namespace NGPP\GmsagcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoldsRepository extends EntityRepository
{
    public function getNewId()
    {
        $result = $this->getEntityManager()
                ->createQuery('SELECT MAX(m.id) FROM NGPPGmsagcBundle:Molds m')
                ->getOneOrNullResult();
        return is_array($result) ? $result[1] + 1 : null;
    }
}
