jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        NGPP\GmsagcBundle\Entity\Users:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        users_provider:
            entity: { class: NGPPGmsagcBundle:Users, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            provider: users_provider
            pattern: ^/
            anonymous: ~
            form_login:
              login_path: /users/login
            logout: ~

    access_control:
        - { path: ^/users/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/, roles: ROLE_USER }
        #- { path: /save|create|delete/i, roles: ROLE_ADMIN }
