login:
    pattern:   /login
    defaults:  { _controller: NGPPGmsagcBundle:Users:login }
login_check:
    pattern:   /login_check
    
ngpp_gmsagc_home:
    pattern:  /
    defaults: { _controller: NGPPGmsagcBundle:Default:index }

ngpp_gmsagc_relations:
    pattern:  /invoices
    defaults: { _controller: NGPPGmsagcBundle:Relations:index }
ngpp_gmsagc_relations_save:
    pattern:  /invoices/save/{id}
    defaults: { _controller: NGPPGmsagcBundle:Relations:save, id: null }
    requirements:
        id:  \d+

ngpp_gmsagc_orders:
    pattern:  /orders
    defaults: { _controller: NGPPGmsagcBundle:Orders:index }
ngpp_gmsagc_orders_save:
    pattern:  /orders/save/{id}
    defaults: { _controller: NGPPGmsagcBundle:Orders:save, id: null }
    requirements:
        id:  \d+
ngpp_gmsagc_orders_delete:
    pattern:  /orders/delete/{id}
    defaults: { _controller: NGPPGmsagcBundle:Orders:delete }
    requirements:
        id:  \d+
        
ngpp_gmsagc_contacts:
    pattern:  /contacts
    defaults: { _controller: NGPPGmsagcBundle:Contacts:index }
ngpp_gmsagc_contacts_save:
    pattern:  /contacts/save/{id}
    defaults: { _controller: NGPPGmsagcBundle:Contacts:save, id: null }
    requirements:
        id:  \d+
ngpp_gmsagc_contacts_delete:
    pattern:  /contacts/delete/{id}
    defaults: { _controller: NGPPGmsagcBundle:Contacts:delete }
    requirements:
        id:  \d+

ngpp_gmsagc_molds:
    pattern:  /molds
    defaults: { _controller: NGPPGmsagcBundle:Molds:index }
ngpp_gmsagc_molds_save:
    pattern:  /molds/save/{id}
    defaults: { _controller: NGPPGmsagcBundle:Molds:save, id: null }
    requirements:
        id:  \d+
ngpp_gmsagc_molds_delete:
    pattern:  /molds/delete/{id}
    defaults: { _controller: NGPPGmsagcBundle:Molds:delete }
    requirements:
        id:  \d+

ngpp_gmsagc_press_list:
    pattern:  /press/list/{name}/{limit}
    defaults: { _controller: NGPPGmsagcBundle:Press:list, name : null, limit: 10 }
    requirements:
        limit:  \d+
    options:
        expose: true
ngpp_gmsagc_materials_list:
    pattern:  /materials/list/{name}/{limit}
    defaults: { _controller: NGPPGmsagcBundle:Materials:list, name : null, limit: 10 }
    requirements:
        limit:  \d+
    options:
        expose: true