login:
    pattern:   /login
    defaults:  { _controller: NGPPGmsagcBundle:Users:login }
login_check:
    pattern:   /login_check
logout:
    path:   /logout

ngpp_gmsagc_home:
    pattern:  /
    defaults: { _controller: NGPPGmsagcBundle:Default:index }

ngpp_gmsagc_relations:
    pattern:  /invoices
    defaults: { _controller: NGPPGmsagcBundle:Relations:index }
ngpp_gmsagc_relations_save:
    pattern:  /invoices/save/{id}
    defaults: { _controller: NGPPGmsagcBundle:Relations:save, id: null }
    requirements:
        id:  \d+

ngpp_gmsagc_orders:
    pattern:  /orders/{page}
    defaults: { _controller: NGPPGmsagcBundle:Orders:index, page: null }
    requirements:
        page:  \d+
ngpp_gmsagc_orders_save:
    pattern:  /orders/save/{id}
    defaults: { _controller: NGPPGmsagcBundle:Orders:save, id: null }
    requirements:
        id:  \d+
ngpp_gmsagc_orders_delete:
    pattern:  /orders/delete/{id}
    defaults: { _controller: NGPPGmsagcBundle:Orders:delete }
    requirements:
        id:  \d+
ngpp_gmsagc_ajax_orders_save:
    pattern:  /ajax/orders/save
    defaults: { _controller: NGPPGmsagcBundle:Orders:ajaxsave }
    requirements:
        id:  \d+

ngpp_gmsagc_contacts:
    pattern:  /contacts/{page}
    defaults: { _controller: NGPPGmsagcBundle:Contacts:index, page: null }
    requirements:
        page:  \d+
ngpp_gmsagc_contacts_save:
    pattern:  /contacts/save/{id}
    defaults: { _controller: NGPPGmsagcBundle:Contacts:save, id: null }
    requirements:
        id:  \d+
ngpp_gmsagc_contacts_delete:
    pattern:  /contacts/delete/{id}
    defaults: { _controller: NGPPGmsagcBundle:Contacts:delete }
    requirements:
        id:  \d+

ngpp_gmsagc_molds:
    pattern:  /molds/{page}
    defaults: { _controller: NGPPGmsagcBundle:Molds:index, page: null }
    requirements:
        page:  \d+
ngpp_gmsagc_molds_save:
    pattern:  /molds/save/{id}
    defaults: { _controller: NGPPGmsagcBundle:Molds:save, id: null }
    requirements:
        id:  \d+
ngpp_gmsagc_molds_delete:
    pattern:  /molds/delete/{id}
    defaults: { _controller: NGPPGmsagcBundle:Molds:delete }
    requirements:
        id:  \d+

ngpp_gmsagc_users:
    pattern:  /users/{page}
    defaults: { _controller: NGPPGmsagcBundle:Users:index, page: null }
    requirements:
        page:  \d+
ngpp_gmsagc_users_save:
    pattern:  /users/save/{id}
    defaults: { _controller: NGPPGmsagcBundle:Users:save, id: null }
    requirements:
        id:  \d+
ngpp_gmsagc_users_password:
    pattern:  /users/password/{id}
    defaults: { _controller: NGPPGmsagcBundle:Users:password, id: null }
    requirements:
        id:  \d+
ngpp_gmsagc_users_delete:
    pattern:  /users/delete/{id}
    defaults: { _controller: NGPPGmsagcBundle:Users:delete }
    requirements:
        id:  \d+
        
ngpp_gmsagc_expenses:
    pattern:  /expenses
    defaults: { _controller: NGPPGmsagcBundle:Expenses:index }
ngpp_gmsagc_expenses_create:
    pattern:  /expenses/create/{order_id}
    defaults: { _controller: NGPPGmsagcBundle:Expenses:create }
    requirements:
        order_id:  \d+
ngpp_gmsagc_expenses_edit:
    pattern:  /expenses/edit/{id}
    defaults: { _controller: NGPPGmsagcBundle:Expenses:edit }
    requirements:
        id:  \d+
ngpp_gmsagc_expenses_delete:
    pattern:  /expenses/delete/{id}
    defaults: { _controller: NGPPGmsagcBundle:Expenses:delete }
    requirements:
        id:  \d+
        
ngpp_gmsagc_hours:
    pattern:  /hours/{order_id}/{week}/{year}
    defaults: { _controller: NGPPGmsagcBundle:Hours:index, week : null, year : null }
    requirements:
        order_id:  \d+
        week: \d+
        year: \d+

ngpp_gmsagc_hours_delete:
    pattern:  /hours/delete/{id}
    defaults: { _controller: NGPPGmsagcBundle:Hours:delete }
    requirements:
        id:  \d+

ngpp_gmsagc_ajax_press_list:
    pattern:  /press/list/{name}/{limit}
    defaults: { _controller: NGPPGmsagcBundle:Press:list, name : null, limit: 10 }
    requirements:
        limit:  \d+
ngpp_gmsagc_ajax_materials_list:
    pattern:  /materials/list/{name}/{limit}
    defaults: { _controller: NGPPGmsagcBundle:Materials:list, name : null, limit: 10 }
    requirements:
        limit:  \d+