parameters:
#    ngpp_gmsagc.example.class: NGPP\GmsagcBundle\Example

services:
#    ngpp_gmsagc.example:
#        class: %ngpp_gmsagc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
