services:
    ngpp_gmsagc.type.press_selector:
        class: NGPP\GmsagcBundle\Form\Type\PressSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: press_selector }
    ngpp_gmsagc.type.material_selector:
        class: NGPP\GmsagcBundle\Form\Type\MaterialSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: material_selector }
    ngpp_gmsagc.form.orders:
        class: NGPP\GmsagcBundle\Form\Type\OrdersType
        arguments: ["@ngpp_gmsagc.form.save_orders_listener"]
        tags:
            - { name: form.type, alias: ngpp_gmsagc_orders_save }
    ngpp_gmsagc.form.molds:
        class: NGPP\GmsagcBundle\Form\Type\MoldsType
        arguments: ["@ngpp_gmsagc.form.save_molds_listener"]
        tags:
            - { name: form.type, alias: ngpp_gmsagc_molds_save }
    ngpp_gmsagc.form.save_orders_listener:
        class: NGPP\GmsagcBundle\Form\EventListener\SaveOrdersListener
        arguments: ["@service_container"]
    ngpp_gmsagc.form.save_molds_listener:
        class: NGPP\GmsagcBundle\Form\EventListener\SaveMoldsListener
        arguments: ["@doctrine.orm.entity_manager"]
    ngpp_gmsagc.form.type.places:
        class: NGPP\GmsagcBundle\Form\Type\PlacesType
        arguments: 
            - "%ngpp_gmsagc.molds_places%"
        tags:
            - { name: form.type, alias: places }