parameters:
#    ngpp_gmsagc.example.class: NGPP\GmsagcBundle\Example

services:
    ngpp_gmsagc.type.press_selector:
        class: NGPP\GmsagcBundle\Form\Type\PressSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: press_selector }
    ngpp_gmsagc.type.material_selector:
        class: NGPP\GmsagcBundle\Form\Type\MaterialSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: material_selector }