parameters:
    ngpp_gmsagc_types:
        owner: 1
        customer: 2
    ngpp_gmsagc_actions:
        creation: 1
        modification: 2
    ngpp_gmsagc_users:
        admin: password
    ngpp_gmsagc_groups:
        ROLE_ADMIN: Admistrators
        ROLE_USER: Users

services:
    ngpp_gmsagc.type.press_selector:
        class: NGPP\GmsagcBundle\Form\Type\PressSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: press_selector }
    ngpp_gmsagc.type.material_selector:
        class: NGPP\GmsagcBundle\Form\Type\MaterialSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: material_selector }
    ngpp_gmsagc.form.orders:
        class: NGPP\GmsagcBundle\Form\Type\OrdersType
        arguments: ["@ngpp_gmsagc.form.save_orders_listener"]
        tags:
            - { name: form.type, alias: ngpp_gmsagc_orders_save }
    ngpp_gmsagc.form.save_orders_listener:
        class: NGPP\GmsagcBundle\Form\EventListener\SaveOrdersListener
        arguments: 
            - "@form.factory"
            - "@doctrine.orm.entity_manager"